from datetime import datetime
from io import BytesIO
from pathlib import Path
from urllib.parse import urlparse

from flask import current_app
from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.util import Inches, Pt

from app.models.system_setting import SystemSetting


class PowerPointExporter:
    """Generate executive PowerPoint cyber security advisories."""

    DEFAULT_PRIMARY_COLOR = "0D6EFD"
    DEFAULT_SECONDARY_COLOR = "6C757D"
    DEFAULT_DANGER_COLOR = "DC3545"
    DEFAULT_WARNING_COLOR = "FFC107"
    DEFAULT_SUCCESS_COLOR = "198754"
    DEFAULT_DARK_COLOR = "212529"
    DEFAULT_LIGHT_COLOR = "F8F9FA"
    DEFAULT_BODY_COLOR = "343A40"

    SLIDE_WIDTH = Inches(13.333)
    SLIDE_HEIGHT = Inches(7.5)

    @staticmethod
    def generate(threat, executive_summary, business_impact, it_recommendation):
        settings = PowerPointExporter._load_settings()

        company_name = settings.get("CompanyName", "Company Name")
        company_short_name = settings.get("CompanyShortName", "")
        department = settings.get("Department", "IT Department")
        classification = settings.get("Classification", "Internal Use")
        company_logo = settings.get("CompanyLogo", "")

        primary_color = PowerPointExporter._parse_hex_color(
            settings.get("PrimaryColor"),
            PowerPointExporter.DEFAULT_PRIMARY_COLOR,
        )
        secondary_color = PowerPointExporter._parse_hex_color(
            settings.get("SecondaryColor"),
            PowerPointExporter.DEFAULT_SECONDARY_COLOR,
        )

        presentation = Presentation()
        presentation.slide_width = PowerPointExporter.SLIDE_WIDTH
        presentation.slide_height = PowerPointExporter.SLIDE_HEIGHT

        core_properties = presentation.core_properties
        core_properties.title = (
            "Cyber Security Advisory - "
            f"{threat.get('CVE') or 'Unknown'}"
        )
        core_properties.subject = (
            threat.get("Title") or "Cyber Security Advisory"
        )
        core_properties.author = department or "IT Department"
        core_properties.company = company_name or "Company Name"
        core_properties.comments = "Generated by CTI Platform"

        common = {
            "company_name": company_name,
            "company_short_name": company_short_name,
            "department": department,
            "classification": classification,
            "company_logo": company_logo,
            "primary_color": primary_color,
            "secondary_color": secondary_color,
        }

        PowerPointExporter._add_cover_slide(
            presentation=presentation,
            threat=threat,
            **common,
        )
        PowerPointExporter._add_overview_slide(
            presentation=presentation,
            threat=threat,
            executive_summary=executive_summary,
            **common,
        )
        PowerPointExporter._add_business_impact_slide(
            presentation=presentation,
            threat=threat,
            business_impact=business_impact,
            **common,
        )
        PowerPointExporter._add_recommendation_slide(
            presentation=presentation,
            threat=threat,
            it_recommendation=it_recommendation,
            **common,
        )
        PowerPointExporter._add_reference_slide(
            presentation=presentation,
            threat=threat,
            **common,
        )

        output = BytesIO()
        presentation.save(output)
        output.seek(0)

        safe_cve = PowerPointExporter._safe_filename(
            str(threat.get("CVE") or "Unknown")
        )
        filename = f"Security_Advisory_{safe_cve}.pptx"
        return output, filename

    @staticmethod
    def _load_settings():
        settings = SystemSetting.query.filter_by(IsActive=True).all()
        return {
            setting.SettingKey: setting.SettingValue or ""
            for setting in settings
        }

    @staticmethod
    def _add_cover_slide(
        presentation,
        threat,
        company_name,
        company_short_name,
        department,
        classification,
        company_logo,
        primary_color,
        secondary_color,
    ):
        slide = presentation.slides.add_slide(presentation.slide_layouts[6])
        PowerPointExporter._set_slide_background(
            slide,
            PowerPointExporter._rgb(PowerPointExporter.DEFAULT_LIGHT_COLOR),
        )
        PowerPointExporter._add_top_brand_bar(
            slide,
            company_name,
            company_short_name,
            department,
            company_logo,
            primary_color,
        )

        severity = PowerPointExporter._normalize_text(
            threat.get("Severity") or "Unknown"
        )
        severity_color = PowerPointExporter._severity_color(severity)
        cve = PowerPointExporter._normalize_text(
            threat.get("CVE") or "No CVE assigned"
        )
        title = PowerPointExporter._normalize_text(
            threat.get("Title") or "Cyber Security Advisory"
        )

        PowerPointExporter._add_textbox(
            slide, Inches(0.85), Inches(1.65), Inches(8.9), Inches(0.7),
            "CYBER SECURITY ADVISORY", Pt(24), True, primary_color,
        )
        PowerPointExporter._add_textbox(
            slide, Inches(0.85), Inches(2.35), Inches(10.8), Inches(1.3),
            title, Pt(29), True,
            PowerPointExporter._rgb(PowerPointExporter.DEFAULT_DARK_COLOR),
        )
        PowerPointExporter._add_textbox(
            slide, Inches(0.85), Inches(3.82), Inches(4.7), Inches(0.55),
            cve, Pt(20), True, secondary_color,
        )
        PowerPointExporter._add_pill(
            slide, Inches(10.1), Inches(3.72), Inches(2.25), Inches(0.65),
            severity.upper(), severity_color,
            PowerPointExporter._contrast_text_color(severity_color),
        )
        PowerPointExporter._add_cover_metrics(
            slide, threat, primary_color, secondary_color
        )
        PowerPointExporter._add_classification_footer(
            slide, classification, company_name,
            primary_color, secondary_color, 1,
        )

    @staticmethod
    def _add_overview_slide(
        presentation,
        threat,
        executive_summary,
        company_name,
        company_short_name,
        department,
        classification,
        company_logo,
        primary_color,
        secondary_color,
    ):
        slide = presentation.slides.add_slide(presentation.slide_layouts[6])
        PowerPointExporter._add_standard_header(
            slide, "Threat Overview", company_name, company_short_name,
            department, company_logo, primary_color,
        )
        PowerPointExporter._add_info_card(
            slide, Inches(0.65), Inches(1.28), Inches(4.05), Inches(4.95),
            "Threat Information", primary_color,
        )

        rows = [
            ("CVE", threat.get("CVE") or "N/A"),
            ("Severity", threat.get("Severity") or "N/A"),
            ("CVSS", threat.get("CVSS") or "N/A"),
            ("Known Exploited", "Yes" if threat.get("KEV") else "No"),
            ("Source", threat.get("Source") or "N/A"),
            ("Published", PowerPointExporter._format_date(
                threat.get("PublishedDate")
            )),
        ]

        y = 2.05
        for label, value in rows:
            PowerPointExporter._add_label_value_row(
                slide, Inches(0.95), Inches(y), Inches(3.45),
                label, PowerPointExporter._normalize_text(value), primary_color,
            )
            y += 0.64

        PowerPointExporter._add_info_card(
            slide, Inches(4.95), Inches(1.28), Inches(7.75), Inches(4.95),
            "Executive Summary", primary_color,
        )
        summary = (
            PowerPointExporter._normalize_multiline_text(executive_summary)
            or "No executive summary available."
        )
        PowerPointExporter._add_body_text(
            slide, Inches(5.25), Inches(2.05), Inches(7.15), Inches(3.75),
            summary, Pt(18),
            PowerPointExporter._rgb(PowerPointExporter.DEFAULT_BODY_COLOR),
        )
        PowerPointExporter._add_classification_footer(
            slide, classification, company_name,
            primary_color, secondary_color, 2,
        )

    @staticmethod
    def _add_business_impact_slide(
        presentation,
        threat,
        business_impact,
        company_name,
        company_short_name,
        department,
        classification,
        company_logo,
        primary_color,
        secondary_color,
    ):
        slide = presentation.slides.add_slide(presentation.slide_layouts[6])
        PowerPointExporter._add_standard_header(
            slide, "Business Impact", company_name, company_short_name,
            department, company_logo, primary_color,
        )
        impact_items = [
            PowerPointExporter._normalize_text(item)
            for item in (business_impact or [])
            if PowerPointExporter._normalize_text(item)
        ]
        if not impact_items:
            impact_items = ["No business impact information available."]

        cards = PowerPointExporter._chunk_items(impact_items, 2)
        left_positions = [0.75, 6.85]
        top_positions = [1.55, 3.95]

        for index, group in enumerate(cards[:4]):
            column = index % 2
            row = index // 2
            PowerPointExporter._add_impact_card(
                slide,
                Inches(left_positions[column]),
                Inches(top_positions[row]),
                Inches(5.72),
                Inches(1.95),
                f"Impact Area {index + 1}",
                group,
                primary_color,
            )

        PowerPointExporter._add_classification_footer(
            slide, classification, company_name,
            primary_color, secondary_color, 3,
        )

    @staticmethod
    def _add_recommendation_slide(
        presentation,
        threat,
        it_recommendation,
        company_name,
        company_short_name,
        department,
        classification,
        company_logo,
        primary_color,
        secondary_color,
    ):
        slide = presentation.slides.add_slide(presentation.slide_layouts[6])
        PowerPointExporter._add_standard_header(
            slide, "IT Recommendation", company_name, company_short_name,
            department, company_logo, primary_color,
        )
        recommendations = PowerPointExporter._split_recommendations(
            it_recommendation
        ) or ["No IT recommendation available."]

        PowerPointExporter._add_info_card(
            slide, Inches(0.75), Inches(1.42), Inches(11.85), Inches(4.95),
            "Recommended Actions", primary_color,
        )
        y = 2.05
        for index, item in enumerate(recommendations[:6], start=1):
            PowerPointExporter._add_numbered_action(
                slide, Inches(1.05), Inches(y), Inches(11.15),
                index, item, primary_color,
            )
            y += 0.68

        PowerPointExporter._add_classification_footer(
            slide, classification, company_name,
            primary_color, secondary_color, 4,
        )

    @staticmethod
    def _add_reference_slide(
        presentation,
        threat,
        company_name,
        company_short_name,
        department,
        classification,
        company_logo,
        primary_color,
        secondary_color,
    ):
        slide = presentation.slides.add_slide(presentation.slide_layouts[6])
        PowerPointExporter._add_standard_header(
            slide, "Source Reference", company_name, company_short_name,
            department, company_logo, primary_color,
        )
        PowerPointExporter._add_info_card(
            slide, Inches(0.85), Inches(1.55), Inches(11.65), Inches(3.65),
            "Reference", primary_color,
        )
        reference_url = PowerPointExporter._normalize_text(
            threat.get("ReferenceUrl") or "No reference URL available."
        )
        PowerPointExporter._add_textbox(
            slide, Inches(1.18), Inches(2.35), Inches(10.95), Inches(1.25),
            reference_url, Pt(18), False, primary_color,
            vertical_anchor=MSO_ANCHOR.MIDDLE,
        )
        if PowerPointExporter._is_valid_web_url(reference_url):
            PowerPointExporter._add_hyperlink_overlay(
                slide, Inches(1.18), Inches(2.35), Inches(10.95), Inches(1.25),
                reference_url,
            )

        generated_text = (
            "Generated by CTI Platform on "
            f"{datetime.now().strftime('%d %b %Y %H:%M')}"
        )
        PowerPointExporter._add_textbox(
            slide, Inches(1.18), Inches(4.15), Inches(10.95), Inches(0.45),
            generated_text, Pt(13), False, secondary_color,
            alignment=PP_ALIGN.RIGHT,
        )
        PowerPointExporter._add_closing_message(slide, primary_color)
        PowerPointExporter._add_classification_footer(
            slide, classification, company_name,
            primary_color, secondary_color, 5,
        )

    @staticmethod
    def _add_top_brand_bar(
        slide, company_name, company_short_name, department,
        company_logo, primary_color,
    ):
        bar = slide.shapes.add_shape(
            MSO_SHAPE.RECTANGLE, 0, 0,
            PowerPointExporter.SLIDE_WIDTH, Inches(0.92),
        )
        bar.fill.solid()
        bar.fill.fore_color.rgb = primary_color
        bar.line.fill.background()

        logo_path = PowerPointExporter._resolve_logo_path(company_logo)
        if logo_path:
            try:
                slide.shapes.add_picture(
                    str(logo_path), Inches(0.55), Inches(0.15),
                    width=Inches(1.35), height=Inches(0.58),
                )
            except (OSError, ValueError):
                PowerPointExporter._add_brand_initials(
                    slide, company_short_name or "CTI",
                    Inches(0.55), Inches(0.18), Inches(1.35), Inches(0.52),
                )
        else:
            PowerPointExporter._add_brand_initials(
                slide, company_short_name or "CTI",
                Inches(0.55), Inches(0.18), Inches(1.35), Inches(0.52),
            )

        PowerPointExporter._add_textbox(
            slide, Inches(7.15), Inches(0.14), Inches(5.55), Inches(0.32),
            company_name or "Company Name", Pt(15), True,
            PowerPointExporter._rgb("FFFFFF"), alignment=PP_ALIGN.RIGHT,
        )
        PowerPointExporter._add_textbox(
            slide, Inches(8.15), Inches(0.5), Inches(4.55), Inches(0.25),
            department or "IT Department", Pt(10), False,
            PowerPointExporter._rgb("FFFFFF"), alignment=PP_ALIGN.RIGHT,
        )

    @staticmethod
    def _add_standard_header(
        slide, title, company_name, company_short_name,
        department, company_logo, primary_color,
    ):
        PowerPointExporter._set_slide_background(
            slide, PowerPointExporter._rgb("FFFFFF")
        )
        PowerPointExporter._add_top_brand_bar(
            slide, company_name, company_short_name,
            department, company_logo, primary_color,
        )
        PowerPointExporter._add_textbox(
            slide, Inches(0.7), Inches(1.0), Inches(7.6), Inches(0.42),
            title, Pt(24), True,
            PowerPointExporter._rgb(PowerPointExporter.DEFAULT_DARK_COLOR),
        )
        accent = slide.shapes.add_shape(
            MSO_SHAPE.RECTANGLE, Inches(0.7), Inches(1.38),
            Inches(1.25), Inches(0.06),
        )
        accent.fill.solid()
        accent.fill.fore_color.rgb = primary_color
        accent.line.fill.background()

    @staticmethod
    def _add_classification_footer(
        slide, classification, company_name,
        primary_color, secondary_color, slide_number,
    ):
        line = slide.shapes.add_shape(
            MSO_SHAPE.RECTANGLE, Inches(0.65), Inches(6.88),
            Inches(12.05), Inches(0.025),
        )
        line.fill.solid()
        line.fill.fore_color.rgb = secondary_color
        line.line.fill.background()
        PowerPointExporter._add_textbox(
            slide, Inches(0.65), Inches(6.94), Inches(4.2), Inches(0.22),
            company_name or "Company Name", Pt(9), False, secondary_color,
        )
        PowerPointExporter._add_textbox(
            slide, Inches(4.85), Inches(6.94), Inches(3.65), Inches(0.22),
            classification or "Internal Use", Pt(9), True, primary_color,
            alignment=PP_ALIGN.CENTER,
        )
        PowerPointExporter._add_textbox(
            slide, Inches(10.7), Inches(6.94), Inches(2.0), Inches(0.22),
            f"Slide {slide_number}", Pt(9), False, secondary_color,
            alignment=PP_ALIGN.RIGHT,
        )

    @staticmethod
    def _add_cover_metrics(slide, threat, primary_color, secondary_color):
        metrics = [
            ("CVSS", PowerPointExporter._normalize_text(
                threat.get("CVSS") or "N/A"
            )),
            ("KNOWN EXPLOITED", "YES" if threat.get("KEV") else "NO"),
            ("PUBLISHED", PowerPointExporter._format_date(
                threat.get("PublishedDate")
            )),
        ]
        lefts = [0.85, 4.5, 8.15]
        for index, (label, value) in enumerate(metrics):
            shape = slide.shapes.add_shape(
                MSO_SHAPE.ROUNDED_RECTANGLE,
                Inches(lefts[index]), Inches(5.08),
                Inches(3.25), Inches(1.15),
            )
            shape.fill.solid()
            shape.fill.fore_color.rgb = PowerPointExporter._rgb("FFFFFF")
            shape.line.color.rgb = PowerPointExporter._lighten_rgb(
                primary_color, 0.72
            )
            shape.line.width = Pt(1.2)
            PowerPointExporter._add_textbox(
                slide, Inches(lefts[index] + 0.22), Inches(5.28),
                Inches(2.8), Inches(0.25), label, Pt(10), True,
                secondary_color,
            )
            PowerPointExporter._add_textbox(
                slide, Inches(lefts[index] + 0.22), Inches(5.58),
                Inches(2.8), Inches(0.4), value, Pt(19), True,
                primary_color,
            )

    @staticmethod
    def _add_info_card(slide, left, top, width, height, heading, primary_color):
        card = slide.shapes.add_shape(
            MSO_SHAPE.ROUNDED_RECTANGLE, left, top, width, height
        )
        card.fill.solid()
        card.fill.fore_color.rgb = PowerPointExporter._rgb("FFFFFF")
        card.line.color.rgb = PowerPointExporter._lighten_rgb(
            primary_color, 0.76
        )
        card.line.width = Pt(1.2)
        header = slide.shapes.add_shape(
            MSO_SHAPE.RECTANGLE, left, top, width, Inches(0.55)
        )
        header.fill.solid()
        header.fill.fore_color.rgb = PowerPointExporter._lighten_rgb(
            primary_color, 0.9
        )
        header.line.fill.background()
        PowerPointExporter._add_textbox(
            slide, left + Inches(0.2), top + Inches(0.12),
            width - Inches(0.4), Inches(0.28), heading,
            Pt(15), True, primary_color,
        )

    @staticmethod
    def _add_label_value_row(
        slide, left, top, width, label, value, primary_color
    ):
        PowerPointExporter._add_textbox(
            slide, left, top, width, Inches(0.2), label.upper(),
            Pt(9), True, PowerPointExporter._lighten_rgb(primary_color, 0.2),
        )
        PowerPointExporter._add_textbox(
            slide, left, top + Inches(0.22), width, Inches(0.32), value,
            Pt(14), True,
            PowerPointExporter._rgb(PowerPointExporter.DEFAULT_DARK_COLOR),
        )

    @staticmethod
    def _add_impact_card(
        slide, left, top, width, height, title, items, primary_color
    ):
        card = slide.shapes.add_shape(
            MSO_SHAPE.ROUNDED_RECTANGLE, left, top, width, height
        )
        card.fill.solid()
        card.fill.fore_color.rgb = PowerPointExporter._lighten_rgb(
            primary_color, 0.93
        )
        card.line.color.rgb = PowerPointExporter._lighten_rgb(
            primary_color, 0.7
        )
        card.line.width = Pt(1.0)
        marker = slide.shapes.add_shape(
            MSO_SHAPE.RECTANGLE, left, top, Inches(0.1), height
        )
        marker.fill.solid()
        marker.fill.fore_color.rgb = primary_color
        marker.line.fill.background()
        PowerPointExporter._add_textbox(
            slide, left + Inches(0.28), top + Inches(0.18),
            width - Inches(0.5), Inches(0.3), title,
            Pt(14), True, primary_color,
        )
        y = top + Inches(0.63)
        for item in items:
            PowerPointExporter._add_textbox(
                slide, left + Inches(0.35), y,
                width - Inches(0.65), Inches(0.45),
                f"• {item}", Pt(14), False,
                PowerPointExporter._rgb(
                    PowerPointExporter.DEFAULT_BODY_COLOR
                ),
            )
            y += Inches(0.55)

    @staticmethod
    def _add_numbered_action(
        slide, left, top, width, number, text, primary_color
    ):
        circle = slide.shapes.add_shape(
            MSO_SHAPE.OVAL, left, top, Inches(0.43), Inches(0.43)
        )
        circle.fill.solid()
        circle.fill.fore_color.rgb = primary_color
        circle.line.fill.background()
        PowerPointExporter._add_textbox(
            slide, left, top + Inches(0.02), Inches(0.43), Inches(0.3),
            str(number), Pt(12), True,
            PowerPointExporter._rgb("FFFFFF"),
            alignment=PP_ALIGN.CENTER,
            vertical_anchor=MSO_ANCHOR.MIDDLE,
        )
        PowerPointExporter._add_textbox(
            slide, left + Inches(0.62), top - Inches(0.01),
            width - Inches(0.62), Inches(0.47), text,
            Pt(15), False,
            PowerPointExporter._rgb(PowerPointExporter.DEFAULT_BODY_COLOR),
            vertical_anchor=MSO_ANCHOR.MIDDLE,
        )

    @staticmethod
    def _add_body_text(
        slide, left, top, width, height, text, font_size, font_color
    ):
        box = slide.shapes.add_textbox(left, top, width, height)
        frame = box.text_frame
        frame.clear()
        frame.word_wrap = True
        frame.margin_left = Inches(0.02)
        frame.margin_right = Inches(0.02)
        frame.margin_top = Inches(0.02)
        frame.margin_bottom = Inches(0.02)
        lines = [
            line.strip()
            for line in str(text or "").splitlines()
            if line.strip()
        ] or [""]
        for index, line in enumerate(lines):
            paragraph = frame.paragraphs[0] if index == 0 else frame.add_paragraph()
            paragraph.text = line
            paragraph.font.name = "Aptos"
            paragraph.font.size = font_size
            paragraph.font.color.rgb = font_color
            paragraph.space_after = Pt(8)
            paragraph.level = 0

    @staticmethod
    def _add_closing_message(slide, primary_color):
        PowerPointExporter._add_textbox(
            slide, Inches(1.0), Inches(5.55), Inches(11.3), Inches(0.5),
            "Stay informed. Assess exposure. Take action.",
            Pt(22), True, primary_color,
            alignment=PP_ALIGN.CENTER,
        )

    @staticmethod
    def _add_pill(
        slide, left, top, width, height, text, fill_color, text_color
    ):
        shape = slide.shapes.add_shape(
            MSO_SHAPE.ROUNDED_RECTANGLE, left, top, width, height
        )
        shape.fill.solid()
        shape.fill.fore_color.rgb = fill_color
        shape.line.fill.background()
        PowerPointExporter._add_textbox(
            slide, left, top + Inches(0.08), width,
            height - Inches(0.1), text, Pt(15), True, text_color,
            alignment=PP_ALIGN.CENTER,
            vertical_anchor=MSO_ANCHOR.MIDDLE,
        )

    @staticmethod
    def _add_brand_initials(slide, text, left, top, width, height):
        PowerPointExporter._add_textbox(
            slide, left, top, width, height, text,
            Pt(18), True, PowerPointExporter._rgb("FFFFFF"),
            vertical_anchor=MSO_ANCHOR.MIDDLE,
        )

    @staticmethod
    def _add_hyperlink_overlay(slide, left, top, width, height, url):
        overlay = slide.shapes.add_shape(
            MSO_SHAPE.RECTANGLE, left, top, width, height
        )
        overlay.fill.background()
        overlay.line.fill.background()
        overlay.click_action.hyperlink.address = url

    @staticmethod
    def _add_textbox(
        slide,
        left,
        top,
        width,
        height,
        text,
        font_size,
        font_bold,
        font_color,
        alignment=PP_ALIGN.LEFT,
        vertical_anchor=MSO_ANCHOR.TOP,
    ):
        shape = slide.shapes.add_textbox(left, top, width, height)
        frame = shape.text_frame
        frame.clear()
        frame.word_wrap = True
        frame.vertical_anchor = vertical_anchor
        frame.margin_left = 0
        frame.margin_right = 0
        frame.margin_top = 0
        frame.margin_bottom = 0
        paragraph = frame.paragraphs[0]
        paragraph.text = str(text or "")
        paragraph.alignment = alignment
        paragraph.font.name = "Aptos"
        paragraph.font.size = font_size
        paragraph.font.bold = font_bold
        paragraph.font.color.rgb = font_color
        return shape

    @staticmethod
    def _set_slide_background(slide, color):
        fill = slide.background.fill
        fill.solid()
        fill.fore_color.rgb = color

    @staticmethod
    def _split_recommendations(value):
        raw_lines = [
            PowerPointExporter._normalize_text(line)
            for line in str(value or "").splitlines()
        ]
        recommendations = []
        for line in raw_lines:
            if not line:
                continue
            cleaned = line.lstrip("•-*0123456789. )(").strip()
            if cleaned:
                recommendations.append(cleaned)
        if recommendations:
            return recommendations
        normalized = PowerPointExporter._normalize_text(value)
        if not normalized:
            return []
        return [
            sentence.strip()
            for sentence in normalized.replace(";", ".").split(".")
            if sentence.strip()
        ]

    @staticmethod
    def _chunk_items(items, chunk_size):
        return [
            items[index:index + chunk_size]
            for index in range(0, len(items), chunk_size)
        ]

    @staticmethod
    def _severity_color(severity):
        normalized = str(severity or "").strip().lower()
        if normalized in {"critical", "severe"}:
            return PowerPointExporter._rgb(
                PowerPointExporter.DEFAULT_DANGER_COLOR
            )
        if normalized == "high":
            return PowerPointExporter._rgb("FD7E14")
        if normalized in {"medium", "moderate"}:
            return PowerPointExporter._rgb(
                PowerPointExporter.DEFAULT_WARNING_COLOR
            )
        if normalized == "low":
            return PowerPointExporter._rgb(
                PowerPointExporter.DEFAULT_SUCCESS_COLOR
            )
        return PowerPointExporter._rgb(
            PowerPointExporter.DEFAULT_SECONDARY_COLOR
        )

    @staticmethod
    def _contrast_text_color(background_color):
        brightness = (
            background_color[0] * 299
            + background_color[1] * 587
            + background_color[2] * 114
        ) / 1000
        return (
            PowerPointExporter._rgb("000000")
            if brightness > 165
            else PowerPointExporter._rgb("FFFFFF")
        )

    @staticmethod
    def _parse_hex_color(value, default_value):
        raw_value = str(value or "").strip().lstrip("#")
        if len(raw_value) != 6:
            raw_value = default_value
        try:
            int(raw_value, 16)
            return PowerPointExporter._rgb(raw_value)
        except (TypeError, ValueError):
            return PowerPointExporter._rgb(default_value)

    @staticmethod
    def _rgb(value):
        raw_value = str(value or "").strip().lstrip("#")
        if len(raw_value) != 6:
            raw_value = "000000"
        try:
            return RGBColor(
                int(raw_value[0:2], 16),
                int(raw_value[2:4], 16),
                int(raw_value[4:6], 16),
            )
        except (TypeError, ValueError):
            return RGBColor(0, 0, 0)

    @staticmethod
    def _lighten_rgb(color, factor):
        safe_factor = min(max(float(factor), 0.0), 1.0)
        red = int(color[0] + (255 - color[0]) * safe_factor)
        green = int(color[1] + (255 - color[1]) * safe_factor)
        blue = int(color[2] + (255 - color[2]) * safe_factor)
        return RGBColor(red, green, blue)

    @staticmethod
    def _normalize_text(value):
        return " ".join(str(value or "").split())

    @staticmethod
    def _normalize_multiline_text(value):
        lines = [
            PowerPointExporter._normalize_text(line)
            for line in str(value or "").splitlines()
        ]
        return "\n".join(line for line in lines if line)

    @staticmethod
    def _format_date(value):
        if value is None:
            return "N/A"
        if hasattr(value, "strftime"):
            return value.strftime("%d %b %Y")
        return str(value)

    @staticmethod
    def _is_valid_web_url(value):
        try:
            parsed = urlparse(str(value))
            return (
                parsed.scheme in {"http", "https"}
                and bool(parsed.netloc)
            )
        except ValueError:
            return False

    @staticmethod
    def _resolve_logo_path(company_logo):
        if not company_logo:
            return None
        raw_path = str(company_logo).strip()
        if not raw_path:
            return None
        normalized_path = raw_path.replace("\\", "/")
        if normalized_path.startswith("/static/"):
            relative_path = normalized_path.removeprefix("/static/")
            candidate = Path(current_app.static_folder) / relative_path
        elif normalized_path.startswith("static/"):
            relative_path = normalized_path.removeprefix("static/")
            candidate = Path(current_app.static_folder) / relative_path
        else:
            candidate = Path(raw_path)
            if not candidate.is_absolute():
                candidate = Path(current_app.root_path) / candidate
        try:
            resolved = candidate.resolve()
        except OSError:
            return None
        return resolved if resolved.is_file() else None

    @staticmethod
    def _safe_filename(value):
        safe_value = str(value or "")
        for character in ["/", "\\", ":", "*", "?", '"', "<", ">", "|"]:
            safe_value = safe_value.replace(character, "-")
        return safe_value.strip() or "Unknown"
